spring.application.name=blog-app-apis

server.port=${PORT:8080}

# DB config (use env variables)
spring.datasource.url=${postgresql://blogapp_postgres_apis_user:erJ0g8MMYYYZJ4rkkZCqYswedN9Akb5p@dpg-d7ai052a214c739rh9lg-a/blogapp_postgres_apis}
spring.datasource.username=${blogapp_postgres_apis_user}
spring.datasource.password=$erJ0g8MMYYYZJ4rkkZCqYswedN9Akb5p}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

project.image=images/

logging.level.org.springframework.security=DEBUG

jwt.secret=${JWT_SECRET}
jwt.expiration=18000